highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://sahibyar.github.io/vitae
author: Sahib Yar

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Sahib Yar's Resume
name: Sahib Yar
email: sahibyaar@hotmail.com
email_full: mailto:sahibyaar@hotmail.com
website: sahibyar.github.io
website_full: https://sahibyar.github.io
my_blogs: /blog.html
github: sahibyar
linkedin: sahibyar
quora: sahib-yar
sound_cloud_full: https://soundcloud.com/sahib-yar
youtube: user/sahibyaar
skype: sahibyaar
stackoverflow: users/2949645/sahib-yar
tel: +92 336 6037321
tel_full: tel:+923366037231
google_maps: 'https://www.google.com/maps/place/Avanza+Solutions+Pvt.+Ltd./@31.5313741,74.3525183,15z/data=!4m5!3m4!1s0x0:0x2bf0e957d3abff63!8m2!3d31.5313741!4d74.3525183'
address: Gulberg 3, Lahore
postcode: 54000
city: Lahore
country: Pakistan
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
